### ISSUE TITLE
Testing: Setup Testing Framework

### ISSUE THREAD

**Issue by TheGreatFez** [TSoGiants/TSoG_X1#1]
We will need to create a system where we can create a Test Case that can then be ran through the simulation, gather data , then evaluate the results.

A Test Case should have the following properties:
1. A description of what the test is testing for
2. Initial conditions of the aircraft
3. Inputs to the aircraft and time stamps of the inputs
4. An associated evaluation function to output a results data structure (note: each test case will have it's own function)

The test cases and any testing utility scripts/functions that get generated from this will be stored in a "Testing" folder at the highest level of the repository.

Additionally, a template Test Case and evaluation function shall be provided as well as a README or text document explaining how to create and run Test Cases.

**Comment by Nufflee** [comment]
I have a couple of questions about this:

1. Are you thinking of test cases as regular Octave scripts or something more sophisticated like a GUI? GUI would certainly be far more complex to develop to the point that it probably won't be worth it but I want to see what you have in mind.
2. What do you mean by "An associated evaluation function to output a results data structure"? Wouldn't that just be the simulation itself which should stay the same between the test cases and only the parameters should change?
3. Do you mind explaining what you would want this loop to look like in general? Would it be something like:
```
1. Write test case script
2. Run script and save results
3. Evaluate results
4. Finish or go back to 1. to tweak it
```

**Comment by TheGreatFez** [comment]
1. The test case should be a script, or even a data file, with the inputs needed to run the simulation.

2. The evaluation function would output a data structure with the results of the evaluation. 

For example, if you ran a test case and wanted a simple pass or fail to see if the plane flew to a certain altitude, the function would parse through the data and if it reached the altitude the result data structure would probably consist of one key with a "true" or "false" if it passes. It doesn't have to be strictly a pass/fail though, it's just a simple example.

3. There is no loop here, the test cases should be self contained. When you run a test case it will run through the test case, then the evaluation script and output the results.
