### ISSUE TITLE
Update Thrust Model with chosen motor and propeller

### ISSUE THREAD

**Issue by TheGreatFez** [TSoGiants/TSoG_X1#27]
The chosen motor can be located [here](https://store.flitetest.com/flite-test-power-pack-a-radial-edition-flt-3057/p983483) in this pack found on Flite Test.

I found [this set of equations](https://forum.openrov.com/t/brushless-motor-calculation/613) for determining lots of different values for a brushless motor.

Currently the model only has a simple linear model based on throttle and airspeed based on arbitrarily chosen values.

This update will determine at least two things:
* Actual Max Static Thrust (Thrust at full power while not moving relative to the air)
* Zero Thrust Max Airspeed

**Comment by Nufflee** [comment]
Have we chosen a motor yet or is this issue blocked currently?

**Comment by adiojha629** [comment]
Link to the motor: https://store.flitetest.com/flite-test-radial-1806-2280kv-brushless-motor-flt-3035/p846361

**Comment by adiojha629** [comment]
At the motor link ([here](https://store.flitetest.com/flite-test-radial-1806-2280kv-brushless-motor-flt-3035/p846361)) we are only given the operating voltage and Kv.

To use the equations in this link ([here](https://forum.openrov.com/t/brushless-motor-calculation/613)) we need to know the motor resistance, or the no load current. These values are absent from the motor's description. I've searched on Amazon to find similar motors, in hopes of finding a data sheet; I have not found such a motor.

These equations help us determine the RPM of the motor. I have used the equation found [here](https://www.electricrcaircraftguy.com/2013/09/propeller-static-dynamic-thrust-equation.html) to determine the thrust based on the RPM.

I suggest that I update the Thrust model with this equation, assuming that the RPM will be about 10,000 rotations per minute. Once the motor is obtained, the required values can be measured and the RPM can be updated. 

[Thrust_update_motor.xlsx](https://github.com/TSoGiants/TSoG_X1/files/4997262/Thrust_update_motor.xlsx)

I've attached a excel spreadsheet. By inputting a specific RPM value, you get an equation for thrust (y) vs. air speed (x).
There is an unfinished sheet that will determine the RPM of the motor; it will be complete once we get necessary values.

**Comment by adiojha629** [comment]
This [Article](https://www.modelairplanenews.com/electric-power-and-the-propeller/#visitor_pref_pop) describes how to go about the motor selection process. (scroll down until you see an A,B,C list). We can work it in reverse to determine the thrust
