### ISSUE TITLE
Simulation: Create an Atmospheric Model

### ISSUE THREAD

**Issue by TheGreatFez** [TSoGiants/TSoG_X1#5]
The model will be used to calculate static pressure, static temperature, and density of air based on altitude.

We can use a standard model from NASA or other sources, please site the source in a comment.

**Comment by Nufflee** [comment]
Is this necessary for the plane itself since it will be (probably) flying at very low altitudes of maybe a couple hundred meters?

**Comment by TheGreatFez** [comment]
Yes, definitely. Not only will this increase the fidelity and accuracy it will set up the ground work for any aerodynamic modeling we want to do with this simulation.

Here is a [link](https://www.grc.nasa.gov/WWW/K-12/airplane/atmosmet.html) to NASA's model if you want to use that, I forgot to add it as a link to the description
